# Generated by Django 5.0.6 on 2024-07-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_alter_level_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Riddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("question", models.TextField()),
                ("answer", models.CharField(max_length=255)),
                ("is_trap", models.BooleanField(default=False)),
                ("code", models.TextField(null=True)),
                ("image", models.TextField(null=True)),
                ("hint", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.level"
                    ),
                ),
            ],
        ),
    ]
