# Generated by Django 5.0.6 on 2024-07-13 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_riddle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riddle",
            name="number",
        ),
        migrations.AddField(
            model_name="riddle",
            name="riddle_id",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 7, 13, 16, 2, 10, 914611, tzinfo=datetime.timezone.utc
                ),
                max_length=10,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
