# Generated by Django 5.0.6 on 2024-07-13 17:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0006_teamprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamProgress",
            new_name="Leaderboard",
        ),
    ]
