# Generated by Django 5.0.6 on 2024-07-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0008_usertrapsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riddle",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="apis.level",
                to_field="number",
            ),
        ),
    ]
